services:
  - type: web
    name: telegram-stats-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN